export interface Country {
  name: string;
  code: string;
  flag: string;
}

export interface City {
  name: string;
  country: string;
}

// Comprehensive world countries data
export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴' },
  { name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧' },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿' },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮' },
  { name: 'Cabo Verde', code: 'CV', flag: '🇨🇻' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦' },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫' },
  { name: 'Chad', code: 'TD', flag: '🇹🇩' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱' },
  { name: 'China', code: 'CN', flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴' },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲' },
  { name: 'Congo', code: 'CG', flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
  { name: 'Democratic Republic of the Congo', code: 'CD', flag: '🇨🇩' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯' },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶' },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷' },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪' },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮' },
  { name: 'France', code: 'FR', flag: '🇫🇷' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦' },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲' },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷' },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹' },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸' },
  { name: 'India', code: 'IN', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹' },
  { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦' },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷' },
  { name: 'Libya', code: 'LY', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮' },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭' },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽' },
  { name: 'Micronesia', code: 'FM', flag: '🇫🇲' },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲' },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬' },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵' },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰' },
  { name: 'Palau', code: 'PW', flag: '🇵🇼' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳' },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧' },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷' },
  { name: 'South Sudan', code: 'SS', flag: '🇸🇸' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { name: 'United States', code: 'US', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺' },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼' },
];

// Comprehensive cities by country data
export const citiesByCountry: Record<string, string[]> = {
  AF: [
    'Kabul',
    'Herat',
    'Kandahar',
    'Mazar-i-Sharif',
    'Kunduz',
    'Jalalabad',
    'Lashkar Gah',
    'Taloqan',
    'Pul-e Khumri',
  ],
  AL: [
    'Tirana',
    'Durrës',
    'Vlorë',
    'Shkodër',
    'Fier',
    'Korçë',
    'Elbasan',
    'Berat',
    'Lushnjë',
  ],
  DZ: [
    'Algiers',
    'Oran',
    'Constantine',
    'Annaba',
    'Blida',
    'Batna',
    'Djelfa',
    'Sétif',
    'Sidi Bel Abbès',
  ],
  AD: [
    'Andorra la Vella',
    'Escaldes-Engordany',
    'Sant Julià de Lòria',
    'Encamp',
    'La Massana',
  ],
  AO: [
    'Luanda',
    'Huambo',
    'Lobito',
    'Benguela',
    'Kuito',
    'Lubango',
    'Malanje',
    'Namibe',
    'Soyo',
  ],
  AG: [
    "Saint John's",
    'All Saints',
    'Liberta',
    "Potter's Village",
    'Bolans',
    'Swetes',
    'Codrington',
  ],
  AR: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'Tucumán',
    'La Plata',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
    'San Juan',
    'Resistencia',
    'Santiago del Estero',
    'Corrientes',
    'Posadas',
    'Bahía Blanca',
    'Paraná',
    'Neuquén',
    'Formosa',
  ],
  AM: [
    'Yerevan',
    'Gyumri',
    'Vanadzor',
    'Vagharshapat',
    'Hrazdan',
    'Abovyan',
    'Kapan',
    'Armavir',
    'Goris',
  ],
  AU: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Newcastle',
    'Canberra',
    'Central Coast',
    'Wollongong',
    'Logan City',
    'Geelong',
    'Hobart',
    'Townsville',
    'Cairns',
    'Darwin',
    'Toowoomba',
  ],
  AT: [
    'Vienna',
    'Graz',
    'Linz',
    'Salzburg',
    'Innsbruck',
    'Klagenfurt',
    'Villach',
    'Wels',
    'Sankt Pölten',
    'Dornbirn',
    'Steyr',
    'Wiener Neustadt',
    'Feldkirch',
    'Bregenz',
    'Leonding',
    'Klosterneuburg',
    'Baden',
    'Wolfsberg',
  ],
  AZ: [
    'Baku',
    'Ganja',
    'Sumqayit',
    'Mingachevir',
    'Qabalä',
    'Lankaran',
    'Nakhchivan',
    'Shaki',
    'Yevlakh',
  ],
  BS: [
    'Nassau',
    'Lucaya',
    'Freeport',
    'West End',
    "Cooper's Town",
    'Marsh Harbour',
    'Nicholls Town',
  ],
  BH: [
    'Manama',
    'Riffa',
    'Muharraq',
    'Hamad Town',
    "A'ali",
    'Isa Town',
    'Sitra',
    'Budaiya',
  ],
  BD: [
    'Dhaka',
    'Chittagong',
    'Khulna',
    'Rajshahi',
    'Sylhet',
    'Rangpur',
    'Barisal',
    'Comilla',
    'Mymensingh',
    'Gazipur',
    'Narayanganj',
    'Bogra',
  ],
  BB: [
    'Bridgetown',
    'Speightstown',
    'Oistins',
    'Bathsheba',
    'Holetown',
    'Crane',
    'Saint Lawrence Gap',
  ],
  BY: [
    'Minsk',
    'Gomel',
    'Mogilev',
    'Vitebsk',
    'Grodno',
    'Brest',
    'Babruysk',
    'Baranovichi',
    'Borisov',
  ],
  BE: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Charleroi',
    'Liège',
    'Bruges',
    'Namur',
    'Leuven',
    'Mons',
    'Aalst',
    'Mechelen',
    'La Louvière',
    'Kortrijk',
    'Hasselt',
    'Sint-Niklaas',
    'Ostend',
    'Tournai',
    'Genk',
  ],
  BZ: [
    'Belize City',
    'San Ignacio',
    'Orange Walk',
    'Belmopan',
    'Dangriga',
    'Corozal',
    'Benque Viejo del Carmen',
  ],
  BJ: [
    'Porto-Novo',
    'Cotonou',
    'Parakou',
    'Djougou',
    'Bohicon',
    'Kandi',
    'Lokossa',
    'Ouidah',
    'Abomey',
  ],
  BT: [
    'Thimphu',
    'Phuntsholing',
    'Punakha',
    'Wangdue',
    'Samdrup Jongkhar',
    'Gelephu',
    'Mongar',
  ],
  BO: [
    'La Paz',
    'Santa Cruz',
    'Cochabamba',
    'Oruro',
    'Sucre',
    'Potosí',
    'Tarija',
    'Trinidad',
    'Cobija',
  ],
  BA: [
    'Sarajevo',
    'Banja Luka',
    'Tuzla',
    'Zenica',
    'Mostar',
    'Prijedor',
    'Brčko',
    'Doboj',
    'Cazin',
  ],
  BW: [
    'Gaborone',
    'Francistown',
    'Molepolole',
    'Maun',
    'Serowe',
    'Selibe Phikwe',
    'Kanye',
    'Mochudi',
  ],
  BR: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Goiânia',
    'Belém',
    'Porto Alegre',
    'Guarulhos',
    'Campinas',
    'São Luís',
    'São Gonçalo',
    'Maceió',
    'Duque de Caxias',
  ],
  BN: [
    'Bandar Seri Begawan',
    'Kuala Belait',
    'Seria',
    'Tutong',
    'Bangar',
    'Muara',
    'Sukang',
  ],
  BG: [
    'Sofia',
    'Plovdiv',
    'Varna',
    'Burgas',
    'Ruse',
    'Stara Zagora',
    'Pleven',
    'Sliven',
    'Dobrich',
  ],
  BF: [
    'Ouagadougou',
    'Bobo-Dioulasso',
    'Koudougou',
    'Banfora',
    'Ouahigouya',
    'Pouytenga',
    'Kaya',
    'Tenkodogo',
  ],
  BI: [
    'Gitega',
    'Bujumbura',
    'Muyinga',
    'Ruyigi',
    'Kayanza',
    'Ngozi',
    'Bururi',
    'Rutana',
    'Makamba',
  ],
  CV: [
    'Praia',
    'Mindelo',
    'Santa Maria',
    'Assomada',
    'Porto Novo',
    'Espargos',
    'Ribeira Grande',
  ],
  KH: [
    'Phnom Penh',
    'Siem Reap',
    'Battambang',
    'Sihanoukville',
    'Poipet',
    'Kampong Cham',
    'Pursat',
  ],
  CM: [
    'Yaoundé',
    'Douala',
    'Garoua',
    'Bamenda',
    'Maroua',
    'Bafoussam',
    'Mokolo',
    'Ngaoundéré',
    'Bertoua',
  ],
  CA: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Kitchener',
    'London',
    'Victoria',
    'Halifax',
    'Windsor',
    'Oshawa',
    'Saskatoon',
    'Regina',
    'Sherbrooke',
  ],
  CF: [
    'Bangui',
    'Bimbo',
    'Berbérati',
    'Carnot',
    'Bambari',
    'Bouar',
    'Bossangoa',
    'Bria',
  ],
  TD: [
    "N'Djamena",
    'Moundou',
    'Sarh',
    'Abéché',
    'Kelo',
    'Koumra',
    'Pala',
    'Am Timan',
    'Bongor',
  ],
  CL: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'La Serena',
    'Antofagasta',
    'Temuco',
    'Rancagua',
    'Talca',
    'Arica',
  ],
  CN: [
    'Shanghai',
    'Beijing',
    'Chongqing',
    'Tianjin',
    'Guangzhou',
    'Shenzhen',
    'Hong Kong',
    'Wuhan',
    'Dongguan',
    'Chengdu',
    'Nanjing',
    'Foshan',
    'Shenyang',
    'Qingdao',
    "Xi'an",
    'Harbin',
    'Hangzhou',
    'Suzhou',
    'Zhengzhou',
    'Macau',
    'Dalian',
    'Xiamen',
    'Kunming',
  ],
  CO: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Soledad',
    'Ibagué',
    'Bucaramanga',
  ],
  KM: [
    'Moroni',
    'Mutsamudu',
    'Fomboni',
    'Domoni',
    'Mitsamiouli',
    'Ouani',
    'Adda-Douéni',
  ],
  CG: [
    'Brazzaville',
    'Pointe-Noire',
    'Dolisie',
    'Nkayi',
    'Mossendjo',
    'Sibiti',
    'Gamboma',
  ],
  CR: [
    'San José',
    'Cartago',
    'Puntarenas',
    'Limón',
    'Alajuela',
    'Heredia',
    'Liberia',
    'Paraíso',
    'Desamparados',
  ],
  HR: [
    'Zagreb',
    'Split',
    'Rijeka',
    'Osijek',
    'Zadar',
    'Pula',
    'Slavonski Brod',
    'Karlovac',
    'Varaždin',
  ],
  CU: [
    'Havana',
    'Santiago de Cuba',
    'Camagüey',
    'Holguín',
    'Guantánamo',
    'Santa Clara',
    'Las Tunas',
    'Bayamo',
  ],
  CY: [
    'Nicosia',
    'Limassol',
    'Larnaca',
    'Famagusta',
    'Paphos',
    'Kyrenia',
    'Protaras',
    'Ayia Napa',
  ],
  CZ: [
    'Prague',
    'Brno',
    'Ostrava',
    'Plzen',
    'Liberec',
    'Olomouc',
    'České Budějovice',
    'Hradec Králové',
  ],
  CD: [
    'Kinshasa',
    'Lubumbashi',
    'Mbuji-Mayi',
    'Kananga',
    'Kisangani',
    'Bukavu',
    'Tshikapa',
    'Kolwezi',
  ],
  DK: [
    'Copenhagen',
    'Aarhus',
    'Odense',
    'Aalborg',
    'Esbjerg',
    'Randers',
    'Kolding',
    'Horsens',
    'Vejle',
    'Roskilde',
    'Herning',
    'Silkeborg',
    'Næstved',
    'Fredericia',
    'Viborg',
    'Køge',
    'Holstebro',
    'Taastrup',
  ],
  DJ: [
    'Djibouti City',
    'Ali Sabieh',
    'Dikhil',
    'Tadjourah',
    'Obock',
    'Arta',
    'Holhol',
  ],
  DM: [
    'Roseau',
    'Portsmouth',
    'Marigot',
    'Berekua',
    'Mahaut',
    'Saint Joseph',
    'Wesley',
  ],
  DO: [
    'Santo Domingo',
    'Santiago',
    'San Pedro de Macorís',
    'La Romana',
    'San Francisco de Macorís',
    'Puerto Plata',
    'La Vega',
  ],
  EC: [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Santo Domingo',
    'Machala',
    'Durán',
    'Manta',
    'Portoviejo',
    'Ambato',
  ],
  EG: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra El Kheima',
    'Port Said',
    'Suez',
    'Luxor',
    'Mansoura',
    'El Mahalla El Kubra',
  ],
  SV: [
    'San Salvador',
    'Soyapango',
    'Santa Ana',
    'San Miguel',
    'Mejicanos',
    'Apopa',
    'Delgado',
    'Ilopango',
  ],
  GQ: ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe', 'Añisoc', 'Luba', 'Evinayong'],
  ER: [
    'Asmara',
    'Keren',
    'Massawa',
    'Assab',
    'Mendefera',
    'Barentu',
    'Adi Keih',
    'Adi Quala',
  ],
  EE: [
    'Tallinn',
    'Tartu',
    'Narva',
    'Pärnu',
    'Kohtla-Järve',
    'Viljandi',
    'Rakvere',
    'Sillamäe',
  ],
  SZ: [
    'Mbabane',
    'Manzini',
    'Lobamba',
    'Siteki',
    'Malkerns',
    'Hluti',
    'Simunye',
  ],
  ET: [
    'Addis Ababa',
    'Dire Dawa',
    "Mek'ele",
    'Gondar',
    'Adama',
    'Awasa',
    'Bahir Dar',
    'Dessie',
    'Jimma',
    'Jijiga',
    'Shashamane',
    'Nekemte',
    'Bishoftu',
    'Asosa',
    'Harar',
    'Dilla',
    'Arba Minch',
    'Hosaena',
  ],
  FJ: [
    'Suva',
    'Lautoka',
    'Nadi',
    'Ba',
    'Labasa',
    'Sigatoka',
    'Nausori',
    'Levuka',
  ],
  FI: [
    'Helsinki',
    'Espoo',
    'Tampere',
    'Vantaa',
    'Oulu',
    'Turku',
    'Jyväskylä',
    'Lahti',
    'Kuopio',
    'Kouvola',
    'Pori',
    'Joensuu',
    'Lappeenranta',
    'Hämeenlinna',
    'Vaasa',
    'Seinäjoki',
    'Rovaniemi',
  ],
  FR: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Saint-Étienne',
    'Toulon',
    'Grenoble',
    'Dijon',
    'Angers',
  ],
  GA: [
    'Libreville',
    'Port-Gentil',
    'Franceville',
    'Oyem',
    'Moanda',
    'Mouila',
    'Lambaréné',
    'Tchibanga',
  ],
  GM: [
    'Banjul',
    'Serekunda',
    'Brikama',
    'Bakau',
    'Lamin',
    'Gunjur',
    'Sukuta',
    'Basse Santa Su',
  ],
  GE: [
    'Tbilisi',
    'Batumi',
    'Kutaisi',
    'Rustavi',
    'Gori',
    'Zugdidi',
    'Poti',
    'Kobuleti',
    'Khashuri',
  ],
  DE: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
  ],
  GH: [
    'Accra',
    'Kumasi',
    'Tamale',
    'Takoradi',
    'Tema',
    'Cape Coast',
    'Koforidua',
    'Sunyani',
    'Ho',
    'Wa',
    'Bolgatanga',
    'Techiman',
    'Obuasi',
    'Nkawkaw',
    'Dunkwa',
    'Tarkwa',
    'Sogakope',
    'Yendi',
  ],
  GR: [
    'Athens',
    'Thessaloniki',
    'Patras',
    'Piraeus',
    'Larissa',
    'Heraklion',
    'Peristeri',
    'Kallithea',
    'Acharnes',
  ],
  GD: [
    "St. George's",
    'Gouyave',
    'Grenville',
    'Victoria',
    "Saint David's",
    'Sauteurs',
  ],
  GT: [
    'Guatemala City',
    'Villa Nueva',
    'Petapa',
    'San Juan Sacatepéquez',
    'Quetzaltenango',
    'Villa Canales',
    'Escuintla',
  ],
  GN: [
    'Conakry',
    'Nzérékoré',
    'Kankan',
    'Kindia',
    'Labe',
    'Mamou',
    'Boke',
    'Faranah',
    'Kissidougou',
  ],
  GW: ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama', 'Cacheu', 'Bubaque'],
  GY: [
    'Georgetown',
    'Linden',
    'New Amsterdam',
    'Bartica',
    'Skeldon',
    'Rosignol',
    'Parika',
  ],
  HT: [
    'Port-au-Prince',
    'Cap-Haïtien',
    'Carrefour',
    'Delmas',
    'Gonaïves',
    'Saint-Marc',
    'Pétion-Ville',
    'Les Cayes',
  ],
  HN: [
    'Tegucigalpa',
    'San Pedro Sula',
    'Choloma',
    'La Ceiba',
    'El Progreso',
    'Choluteca',
    'Comayagua',
    'Puerto Cortés',
  ],
  HU: [
    'Budapest',
    'Debrecen',
    'Szeged',
    'Miskolc',
    'Pécs',
    'Győr',
    'Nyíregyháza',
    'Kecskemét',
    'Székesfehérvár',
  ],
  IS: [
    'Reykjavik',
    'Akureyri',
    'Reykjanesbær',
    'Akranes',
    'Hafnarfjörður',
    'Garðabær',
    'Kópavogur',
    'Mosfellsbær',
  ],
  IN: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Pimpri-Chinchwad',
  ],
  ID: [
    'Jakarta',
    'Surabaya',
    'Medan',
    'Bekasi',
    'Bandung',
    'Tangerang',
    'Depok',
    'Semarang',
    'Palembang',
    'Makassar',
    'South Tangerang',
    'Batam',
    'Bogor',
    'Pekanbaru',
  ],
  IR: [
    'Tehran',
    'Mashhad',
    'Isfahan',
    'Karaj',
    'Tabriz',
    'Shiraz',
    'Ahvaz',
    'Qom',
    'Kermanshah',
    'Urmia',
    'Rasht',
    'Zahedan',
  ],
  IQ: [
    'Baghdad',
    'Basra',
    'Mosul',
    'Erbil',
    'Sulaymaniyah',
    'Najaf',
    'Karbala',
    'Nasiriyah',
    'Amarah',
    'Duhok',
    'Samarra',
    'Fallujah',
  ],
  IE: [
    'Dublin',
    'Cork',
    'Limerick',
    'Galway',
    'Waterford',
    'Drogheda',
    'Dundalk',
    'Swords',
    'Bray',
  ],
  IL: [
    'Jerusalem',
    'Tel Aviv',
    'Haifa',
    'Rishon LeZion',
    'Petah Tikva',
    'Ashdod',
    'Netanya',
    'Beer Sheva',
    'Holon',
  ],
  IT: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Bari',
    'Catania',
    'Venice',
    'Verona',
    'Messina',
    'Padua',
    'Trieste',
    'Taranto',
    'Brescia',
    'Prato',
  ],
  CI: [
    'Abidjan',
    'Bouaké',
    'Daloa',
    'Yamoussoukro',
    'San-Pédro',
    'Korhogo',
    'Man',
    'Divo',
    'Gagnoa',
  ],
  JM: [
    'Kingston',
    'Spanish Town',
    'Portmore',
    'Montego Bay',
    'May Pen',
    'Mandeville',
    'Old Harbour',
    'Savanna-la-Mar',
  ],
  JP: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kawasaki',
    'Kyoto',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Kitakyushu',
    'Chiba',
    'Sakai',
    'Niigata',
    'Hamamatsu',
    'Okayama',
  ],
  JO: [
    'Amman',
    'Zarqa',
    'Irbid',
    'Russeifa',
    'Quwaysima',
    'Wadi as-Sir',
    'Aqaba',
    'Madaba',
    'Salt',
  ],
  KZ: [
    'Almaty',
    'Nur-Sultan',
    'Shymkent',
    'Aktobe',
    'Taraz',
    'Pavlodar',
    'Ust-Kamenogorsk',
    'Semey',
    'Atyrau',
  ],
  KE: [
    'Nairobi',
    'Mombasa',
    'Nakuru',
    'Eldoret',
    'Kisumu',
    'Thika',
    'Malindi',
    'Kitale',
    'Garissa',
    'Kakamega',
    'Nyeri',
    'Machakos',
    'Meru',
    'Kericho',
    'Embu',
    'Migori',
    'Homa Bay',
    'Naivasha',
  ],
  KI: ['Tarawa', 'Betio', 'Bikenibeu', 'Teaoraereke'],
  KW: [
    'Kuwait City',
    'Al Ahmadi',
    'Hawalli',
    'As Salimiyah',
    'Sabah as Salim',
    'Al Farwaniyah',
    'Al Fahaheel',
  ],
  KG: [
    'Bishkek',
    'Osh',
    'Jalal-Abad',
    'Karakol',
    'Tokmok',
    'Uzgen',
    'Naryn',
    'Talas',
    'Batken',
  ],
  LA: [
    'Vientiane',
    'Pakse',
    'Savannakhet',
    'Luang Prabang',
    'Phonsavan',
    'Xam Neua',
    'Thakhek',
    'Muang Xay',
  ],
  LV: [
    'Riga',
    'Daugavpils',
    'Liepāja',
    'Jelgava',
    'Jūrmala',
    'Ventspils',
    'Rēzekne',
    'Valmiera',
    'Jēkabpils',
  ],
  LB: [
    'Beirut',
    'Tripoli',
    'Sidon',
    'Tyre',
    'Nabatieh',
    'Jounieh',
    'Zahle',
    'Baalbek',
    'Byblos',
  ],
  LS: [
    'Maseru',
    'Teyateyaneng',
    'Mafeteng',
    'Hlotse',
    "Mohale's Hoek",
    'Maputsoe',
    "Qacha's Nek",
    'Quthing',
  ],
  LR: [
    'Monrovia',
    'Gbarnga',
    'Kakata',
    'Bensonville',
    'Harper',
    'Voinjama',
    'Buchanan',
    'Zwedru',
  ],
  LY: [
    'Tripoli',
    'Benghazi',
    'Misrata',
    'Tarhuna',
    'Al Bayda',
    'Zawiya',
    'Zliten',
    'Ajdabiya',
    'Tobruk',
  ],
  LI: [
    'Vaduz',
    'Schaan',
    'Balzers',
    'Triesen',
    'Eschen',
    'Mauren',
    'Triesenberg',
  ],
  LT: [
    'Vilnius',
    'Kaunas',
    'Klaipėda',
    'Šiauliai',
    'Panevėžys',
    'Alytus',
    'Marijampolė',
    'Mažeikiai',
    'Jonava',
  ],
  LU: [
    'Luxembourg City',
    'Esch-sur-Alzette',
    'Dudelange',
    'Differdange',
    'Sanem',
    'Bettembourg',
    'Pétange',
  ],
  MG: [
    'Antananarivo',
    'Toamasina',
    'Antsirabe',
    'Fianarantsoa',
    'Mahajanga',
    'Toliara',
    'Antsiranana',
    'Ambovombe',
  ],
  MW: [
    'Lilongwe',
    'Blantyre',
    'Mzuzu',
    'Zomba',
    'Kasungu',
    'Mangochi',
    'Karonga',
    'Salima',
    'Liwonde',
  ],
  MY: [
    'Kuala Lumpur',
    'George Town',
    'Ipoh',
    'Shah Alam',
    'Petaling Jaya',
    'Klang',
    'Johor Bahru',
    'Subang Jaya',
    'Kuching',
    'Kota Kinabalu',
    'Seremban',
    'Malacca City',
  ],
  MV: [
    'Malé',
    'Addu City',
    'Fuvahmulah',
    'Kulhudhuffushi',
    'Thinadhoo',
    'Ungoofaaru',
    'Naifaru',
  ],
  ML: [
    'Bamako',
    'Sikasso',
    'Mopti',
    'Koutiala',
    'Ségou',
    'Kayes',
    'Gao',
    'Tombouctou',
    'Kati',
  ],
  MT: [
    'Valletta',
    'Birgu',
    'Birkirkara',
    'Qormi',
    'Mosta',
    'Żabbar',
    'San Pawl il-Baħar',
    'Fgura',
  ],
  MH: ['Majuro', 'Ebeye', 'Laura', 'Wotje', 'Mili', 'Arno'],
  MR: [
    'Nouakchott',
    'Nouadhibou',
    'Néma',
    'Kaédi',
    'Rosso',
    'Zouérat',
    'Atar',
    'Selibaby',
  ],
  MU: [
    'Port Louis',
    'Beau Bassin-Rose Hill',
    'Vacoas-Phoenix',
    'Curepipe',
    'Quatre Bornes',
    'Triolet',
  ],
  MX: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Torreón',
    'Querétaro',
    'San Luis Potosí',
    'Mérida',
    'Mexicali',
    'Aguascalientes',
    'Cuernavaca',
    'Saltillo',
    'Hermosillo',
    'Culiacán',
    'Morelia',
  ],
  FM: ['Palikir', 'Weno', 'Tofol', 'Colonia'],
  MD: [
    'Chișinău',
    'Tiraspol',
    'Bălți',
    'Bender',
    'Rîbnița',
    'Cahul',
    'Ungheni',
    'Soroca',
  ],
  MC: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'],
  MN: [
    'Ulaanbaatar',
    'Erdenet',
    'Darkhan',
    'Choibalsan',
    'Murun',
    'Uliastai',
    'Hovd',
    'Bayankhongor',
  ],
  ME: [
    'Podgorica',
    'Nikšić',
    'Pljevlja',
    'Bijelo Polje',
    'Cetinje',
    'Bar',
    'Herceg Novi',
    'Berane',
  ],
  MA: [
    'Casablanca',
    'Rabat',
    'Fès',
    'Marrakech',
    'Agadir',
    'Tangier',
    'Meknès',
    'Oujda',
    'Kenitra',
    'Tetouan',
    'Safi',
    'Mohammedia',
  ],
  MZ: [
    'Maputo',
    'Matola',
    'Nampula',
    'Beira',
    'Chimoio',
    'Nacala',
    'Quelimane',
    'Tete',
    'Xai-Xai',
  ],
  MM: [
    'Yangon',
    'Mandalay',
    'Naypyitaw',
    'Mawlamyine',
    'Bago',
    'Pathein',
    'Monywa',
    'Meiktila',
    'Myitkyina',
  ],
  NA: [
    'Windhoek',
    'Rundu',
    'Walvis Bay',
    'Swakopmund',
    'Oshakati',
    'Rehoboth',
    'Katima Mulilo',
    'Otjiwarongo',
  ],
  NR: ['Yaren', 'Aiwo', 'Anabar', 'Anetan', 'Anibare', 'Baiti', 'Boe', 'Buada'],
  NP: [
    'Kathmandu',
    'Pokhara',
    'Lalitpur',
    'Bharatpur',
    'Biratnagar',
    'Birgunj',
    'Dharan',
    'Butwal',
    'Hetauda',
  ],
  NL: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
    'Enschede',
    'Haarlem',
    'Arnhem',
    'Zaanstad',
    'Amersfoort',
    'Apeldoorn',
    'Dordrecht',
    'Leiden',
  ],
  NZ: [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Hamilton',
    'Tauranga',
    'Dunedin',
    'Palmerston North',
    'Napier',
    'Porirua',
    'Rotorua',
    'New Plymouth',
    'Whangārei',
    'Invercargill',
    'Nelson',
  ],
  NI: [
    'Managua',
    'León',
    'Masaya',
    'Matagalpa',
    'Chinandega',
    'Granada',
    'Jinotega',
    'Estelí',
    'Corinto',
  ],
  NE: [
    'Niamey',
    'Zinder',
    'Maradi',
    'Agadez',
    'Tahoua',
    'Dosso',
    'Tillabéri',
    'Diffa',
  ],
  NG: [
    'Lagos',
    'Kano',
    'Ibadan',
    'Kaduna',
    'Port Harcourt',
    'Benin City',
    'Maiduguri',
    'Zaria',
    'Aba',
    'Jos',
    'Ilorin',
    'Oyo',
    'Enugu',
    'Abeokuta',
    'Abuja',
    'Sokoto',
    'Onitsha',
    'Warri',
  ],
  KP: [
    'Pyongyang',
    'Hamhung',
    'Chongjin',
    'Nampo',
    'Wonsan',
    'Sinuiju',
    'Tanchon',
    'Kaechon',
  ],
  MK: [
    'Skopje',
    'Kumanovo',
    'Bitola',
    'Tetovo',
    'Veles',
    'Štip',
    'Ohrid',
    'Gostivar',
    'Strumica',
  ],
  NO: [
    'Oslo',
    'Bergen',
    'Stavanger',
    'Trondheim',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Sandnes',
    'Tromsø',
    'Sarpsborg',
    'Skien',
    'Ålesund',
    'Sandefjord',
    'Haugesund',
    'Tønsberg',
    'Moss',
    'Arendal',
    'Bodø',
  ],
  OM: [
    'Muscat',
    'Seeb',
    'Salalah',
    'Bawshar',
    'Sohar',
    'As Suwayq',
    'Ibri',
    'Saham',
    'Barka',
  ],
  PK: [
    'Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Gujranwala',
    'Peshawar',
    'Multan',
    'Islamabad',
    'Quetta',
    'Sialkot',
    'Bahawalpur',
    'Sargodha',
  ],
  PW: ['Ngerulmud', 'Koror', 'Airai', 'Melekeok'],
  PA: [
    'Panama City',
    'San Miguelito',
    'Tocumen',
    'David',
    'Arraiján',
    'Colón',
    'La Chorrera',
    'Pacora',
  ],
  PG: [
    'Port Moresby',
    'Lae',
    'Mount Hagen',
    'Popondetta',
    'Madang',
    'Wewak',
    'Vanimo',
    'Kimbe',
  ],
  PY: [
    'Asunción',
    'Ciudad del Este',
    'Luque',
    'San Lorenzo',
    'Capiatá',
    'Lambaré',
    'Fernando de la Mora',
    'Limpio',
  ],
  PE: [
    'Lima',
    'Arequipa',
    'Callao',
    'Trujillo',
    'Chiclayo',
    'Piura',
    'Iquitos',
    'Cusco',
    'Chimbote',
    'Huancayo',
    'Tacna',
    'Juliaca',
  ],
  PH: [
    'Quezon City',
    'Manila',
    'Caloocan',
    'Davao',
    'Cebu City',
    'Zamboanga',
    'Taguig',
    'Antipolo',
    'Pasig',
    'Cagayan de Oro',
    'Parañaque',
    'Valenzuela',
  ],
  PL: [
    'Warsaw',
    'Krakow',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Białystok',
    'Katowice',
    'Gdynia',
  ],
  PT: [
    'Lisbon',
    'Porto',
    'Amadora',
    'Braga',
    'Setúbal',
    'Coimbra',
    'Queluz',
    'Funchal',
    'Cacém',
    'Vila Nova de Gaia',
    'Loures',
    'Évora',
    'Rio Tinto',
    'Odivelas',
    'Aveiro',
    'Corroios',
    'Barreiro',
    'Montijo',
  ],
  QA: [
    'Doha',
    'Al Rayyan',
    'Umm Salal',
    'Al Khor',
    'Al Wakrah',
    'Dukhan',
    'Lusail',
    'Mesaieed',
  ],
  RO: [
    'Bucharest',
    'Cluj-Napoca',
    'Timișoara',
    'Iași',
    'Constanța',
    'Craiova',
    'Brașov',
    'Galați',
    'Ploiești',
  ],
  RU: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Nizhny Novgorod',
    'Kazan',
    'Chelyabinsk',
    'Omsk',
    'Samara',
    'Rostov-on-Don',
    'Ufa',
    'Krasnoyarsk',
  ],
  RW: [
    'Kigali',
    'Butare',
    'Gitarama',
    'Ruhengeri',
    'Gisenyi',
    'Byumba',
    'Cyangugu',
    'Kibungo',
  ],
  KN: [
    'Basseterre',
    'Charlestown',
    'Dieppe Bay Town',
    'Oistins',
    'Sandy Point Town',
  ],
  LC: ['Castries', 'Bisee', 'Vieux Fort', 'Micoud', 'Soufrière', 'Dennery'],
  VC: [
    'Kingstown',
    'Georgetown',
    'Barrouallie',
    'Port Elizabeth',
    'Layou',
    'Calliaqua',
  ],
  WS: ['Apia', 'Salelologa', 'Mulifanua', 'Leulumoega', 'Lufilufi'],
  SM: ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'],
  ST: ['São Tomé', 'Santo António', 'Neves', 'Santana', 'Guadalupe'],
  SA: [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    'Tabuk',
    'Buraydah',
    'Khamis Mushait',
    'Hail',
    'Hafar Al-Batin',
    'Jubail',
  ],
  SN: [
    'Dakar',
    'Touba',
    'Thiès',
    'Kaolack',
    'Saint-Louis',
    'Ziguinchor',
    'Kolda',
    'Diourbel',
    'Tambacounda',
  ],
  RS: [
    'Belgrade',
    'Novi Sad',
    'Niš',
    'Kragujevac',
    'Subotica',
    'Novi Pazar',
    'Zrenjanin',
    'Pančevo',
    'Čačak',
  ],
  SC: [
    'Victoria',
    'Anse Boileau',
    'Beau Vallon',
    'Takamaka',
    'Cascade',
    'Port Glaud',
  ],
  SL: [
    'Freetown',
    'Bo',
    'Kenema',
    'Koidu',
    'Makeni',
    'Lunsar',
    'Port Loko',
    'Waterloo',
  ],
  SG: [
    'Singapore',
    'Jurong West',
    'Woodlands',
    'Tampines',
    'Sengkang',
    'Hougang',
    'Yishun',
    'Bedok',
  ],
  SK: [
    'Bratislava',
    'Košice',
    'Prešov',
    'Žilina',
    'Banská Bystrica',
    'Nitra',
    'Trnava',
    'Martin',
    'Trenčín',
  ],
  SI: [
    'Ljubljana',
    'Maribor',
    'Celje',
    'Kranj',
    'Velenje',
    'Koper',
    'Novo Mesto',
    'Ptuj',
    'Trbovlje',
  ],
  SB: ['Honiara', 'Gizo', 'Auki', 'Kirakira', 'Buala', 'Tulagi', 'Lata'],
  SO: [
    'Mogadishu',
    'Hargeisa',
    'Bosaso',
    'Kismayo',
    'Baydhabo',
    'Galkayo',
    'Berbera',
    'Merca',
  ],
  ZA: [
    'Cape Town',
    'Johannesburg',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
    'Nelspruit',
    'Polokwane',
    'Kimberley',
    'Rustenburg',
    'George',
    'Pietermaritzburg',
    'Potchefstroom',
    'Welkom',
    'Klerksdorp',
    'Witbank',
    'Midrand',
  ],
  KR: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Ulsan',
    'Changwon',
    'Goyang',
    'Yongin',
    'Seongnam',
    'Bucheon',
    'Cheongju',
    'Ansan',
    'Jeonju',
    'Anyang',
    'Cheonan',
  ],
  SS: ['Juba', 'Malakal', 'Wau', 'Yei', 'Bentiu', 'Bor', 'Yambio', 'Kuacjok'],
  ES: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
    'Granada',
    'A Coruña',
    'Vitoria',
  ],
  LK: [
    'Colombo',
    'Dehiwala-Mount Lavinia',
    'Moratuwa',
    'Negombo',
    'Kandy',
    'Kalmunai',
    'Trincomalee',
    'Galle',
    'Jaffna',
  ],
  SD: [
    'Khartoum',
    'Omdurman',
    'Khartoum North',
    'Nyala',
    'Port Sudan',
    'Kassala',
    'Al-Ubayyid',
    'Al-Qadarif',
    'Wad Madani',
  ],
  SR: [
    'Paramaribo',
    'Lelydorp',
    'Brokopondo',
    'Nieuw Nickerie',
    'Moengo',
    'Marienburg',
    'Wageningen',
  ],
  SE: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Jönköping',
    'Norrköping',
    'Lund',
    'Umeå',
    'Gävle',
    'Borås',
    'Södertälje',
    'Eskilstuna',
    'Halmstad',
    'Växjö',
  ],
  CH: [
    'Zurich',
    'Geneva',
    'Basel',
    'Bern',
    'Lausanne',
    'Winterthur',
    'Lucerne',
    'St. Gallen',
    'Lugano',
    'Biel',
    'Thun',
    'Köniz',
    'La Chaux-de-Fonds',
    'Schaffhausen',
    'Fribourg',
    'Vernier',
  ],
  SY: [
    'Damascus',
    'Aleppo',
    'Homs',
    'Latakia',
    'Hama',
    'Deir ez-Zor',
    'Raqqa',
    'Daraa',
    'Hasakah',
  ],
  TW: [
    'Taipei',
    'Kaohsiung',
    'Taichung',
    'Tainan',
    'Taoyuan',
    'New Taipei',
    'Hsinchu',
    'Keelung',
    'Chiayi',
  ],
  TJ: [
    'Dushanbe',
    'Khujand',
    'Kulob',
    'Qurghonteppa',
    'Istaravshan',
    'Panjakent',
    'Tursunzoda',
    'Vahdat',
  ],
  TZ: [
    'Dar es Salaam',
    'Mwanza',
    'Arusha',
    'Dodoma',
    'Mbeya',
    'Morogoro',
    'Tanga',
    'Kahama',
    'Tabora',
  ],
  TH: [
    'Bangkok',
    'Samut Prakan',
    'Mueang Nonthaburi',
    'Udon Thani',
    'Chon Buri',
    'Nakhon Ratchasima',
    'Chiang Mai',
    'Hat Yai',
    'Pak Kret',
  ],
  TL: ['Dili', 'Dare', 'Baucau', 'Maliana', 'Suai', 'Same', 'Ainaro', 'Aileu'],
  TG: [
    'Lomé',
    'Sokodé',
    'Kara',
    'Palimé',
    'Atakpamé',
    'Bassar',
    'Tsévié',
    'Aného',
  ],
  TO: ["Nuku'alofa", 'Neiafu', 'Haveluloto', 'Vaini', 'Pangai', 'Ohonua'],
  TT: [
    'Port of Spain',
    'San Fernando',
    'Chaguanas',
    'Arima',
    'Point Fortin',
    'Laventille',
    'Princes Town',
  ],
  TN: [
    'Tunis',
    'Sfax',
    'Sousse',
    'Kairouan',
    'Bizerte',
    'Gabès',
    'Ariana',
    'Gafsa',
    'Monastir',
  ],
  TR: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Adana',
    'Gaziantep',
    'Konya',
    'Çankaya',
    'Antalya',
    'Bağcılar',
    'Diyarbakır',
    'Kayseri',
  ],
  TM: [
    'Ashgabat',
    'Turkmenbashi',
    'Türkmenabat',
    'Mary',
    'Balkanabat',
    'Bayramaly',
    'Serdar',
    'Tejen',
  ],
  TV: ['Funafuti', 'Asau', 'Lolua', 'Savave', 'Tanrake', 'Toga'],
  UG: [
    'Kampala',
    'Gulu',
    'Lira',
    'Mbarara',
    'Jinja',
    'Bwizibwera',
    'Mbale',
    'Mukono',
    'Kasese',
  ],
  UA: [
    'Kyiv',
    'Kharkiv',
    'Odesa',
    'Dnipro',
    'Donetsk',
    'Zaporizhzhia',
    'Lviv',
    'Kryvyi Rih',
    'Mykolaiv',
  ],
  AE: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Al Ain',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
  ],
  GB: [
    'London',
    'Birmingham',
    'Manchester',
    'Liverpool',
    'Leeds',
    'Sheffield',
    'Bristol',
    'Glasgow',
    'Leicester',
    'Edinburgh',
    'Newcastle',
    'Brighton',
    'Portsmouth',
    'Southampton',
    'Reading',
    'Derby',
    'Plymouth',
    'Luton',
  ],
  US: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington DC',
    'Boston',
    'Las Vegas',
    'Miami',
  ],
  UY: [
    'Montevideo',
    'Salto',
    'Paysandú',
    'Las Piedras',
    'Rivera',
    'Maldonado',
    'Tacuarembó',
    'Melo',
    'Mercedes',
  ],
  UZ: [
    'Tashkent',
    'Namangan',
    'Samarkand',
    'Andijan',
    'Nukus',
    'Fergana',
    'Bukhara',
    'Qarshi',
    'Kokand',
  ],
  VU: ['Port Vila', 'Luganville', 'Isangel', 'Sola', 'Lenakel', 'Lakatoro'],
  VA: ['Vatican City'],
  VE: [
    'Caracas',
    'Maracaibo',
    'Valencia',
    'Barquisimeto',
    'Maracay',
    'Ciudad Guayana',
    'San Cristóbal',
    'Maturín',
    'Ciudad Bolívar',
  ],
  VN: [
    'Ho Chi Minh City',
    'Hanoi',
    'Haiphong',
    'Da Nang',
    'Bien Hoa',
    'Hue',
    'Nha Trang',
    'Can Tho',
    'Rach Gia',
  ],
  YE: [
    'Sanaa',
    'Aden',
    'Taiz',
    'Al Hudaydah',
    'Mukalla',
    'Ibb',
    'Dhamar',
    'Amran',
    'Saada',
  ],
  ZM: [
    'Lusaka',
    'Kitwe',
    'Ndola',
    'Kabwe',
    'Chingola',
    'Mufulira',
    'Livingstone',
    'Luanshya',
    'Kasama',
  ],
  ZW: [
    'Harare',
    'Bulawayo',
    'Chitungwiza',
    'Mutare',
    'Epworth',
    'Gweru',
    'Kwekwe',
    'Kadoma',
    'Masvingo',
  ],
};

export const getCitiesForCountry = (countryCode: string): string[] => {
  return citiesByCountry[countryCode] || [];
};

export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find((country) => country.code === code);
};
